const items = [
    {
        id: 1,
        title: "Capsicum",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000068_22-fresho-capsicum-green.jpg",
        price: 75,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: true
    },
    {
        id: 2,
        title: "Carrot",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000071_14-fresho-carrot-orange.jpg",
        price: 35,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: true
    },
    {
        id: 3,
        title: "Onion",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000148_30-fresho-onion.jpg",
        price: 50,
        discount: 10,
        quantity: 1,
        category: "Vegetables",
        featured: false
    },
    {
        id: 4,
        title: "Potato",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000159_27-fresho-potato.jpg",
        price: 50,
        discount: 15,
        quantity: 1,
        category: "Vegetables",
        featured: false
    },
    {
        id: 5,
        title: "Tomato",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000204_16-fresho-tomato-local.jpg",
        price: 100,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: false
    },
    {
        id: 6,
        title: "Cucumber",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000103_16-fresho-cucumber.jpg",
        price: 25,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: false
    },
    {
        id: 7,
        title: "CauliFlower",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000074_19-fresho-cauliflower.jpg",
        price: 50,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: true
    },
    {
        id: 8,
        title: "Beans",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/40089742_2-fresho-beans-haricot.jpg",
        price: 100,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: false
    },
    {
        id: 9,
        title: "Mushroom",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000273_16-fresho-mushrooms-button.jpg",
        price: 80,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: true
    },
    {
        id: 10,
        title: "Cabbage",
        description: "Vegetable",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000066_25-fresho-cabbage.jpg",
        price: 40,
        discount: 5,
        quantity: 1,
        category: "Vegetables",
        featured: true
    },
    {
        id: 11,
        title: "Coconut",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/1221868_1-fresho-tender-coconut.jpg",
        price: 350,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: false
    },
    {
        id: 12,
        title: "Mango",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000304_4-fresho-mallika-mango.jpg",
        price: 150,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: true
    },
    {
        id: 13,
        title: "Banana",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000033_25-fresho-banana-yelakki.jpg",
        price: 75,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: true
    },
    {
        id: 14,
        title: "Pomegranate",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/40120006_5-fresho-pomegranate-small.jpg",
        price: 320,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: false
    },
    {
        id: 15,
        title: "Water Melon",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000207_24-fresho-watermelon-small.jpg",
        price: 120,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: true
    },
    {
        id: 16,
        title: "Apple",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/10000005_27-fresho-apple-royal-gala-economy.jpg",
        price: 200,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: true
    },
    {
        id: 17,
        title: "Kiwi",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/20000911_30-fresho-kiwi-green.jpg",
        price: 200,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: true
    },
    {
        id: 18,
        title: "Blue Berry",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/30009286_7-fresho-blueberry.jpg",
        price: 350,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: false
    },
    {
        id: 19,
        title: "Dragon Fruit",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/40008982_15-fresho-dragon-fruit.jpg",
        price: 100,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: false
    },
    {
        id: 20,
        title: "pear",
        description: "Fruit",
        image: "https://www.bigbasket.com/media/uploads/p/s/40048445_2-fresho-pear-green-imported.jpg",
        price: 200,
        discount: 5,
        quantity: 1,
        category: "Fruits",
        featured: false
    },
    {
        id: 21,
        title: "Milk",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/242671_1-nandini-goodlife-toned-milk.jpg",
        price: 30,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: true
    },
    {
        id: 22,
        title: "Curd",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/40003156_8-milky-mist-natural-set-curd.jpg",
        price: 100,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: false
    },
    {
        id: 23,
        title: "Paneer",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/264679_5-milky-mist-paneer-premium-fresh.jpg",
        price: 150,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: true
    },
    {
        id: 24,
        title: "Butter",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/1204991_3-amul-butter-pasteurized.jpg",
        price: 250,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: true
    },
    {
        id: 25,
        title: "Butter Milk",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/180584_8-amul-masti-buttermilk-spice.jpg",
        price: 70,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: false
    },
    {
        id: 26,
        title: "MilkShake",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/1202881_5-hersheys-milk-shake-chocolate.jpg",
        price: 90,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: true
    },
    {
        id: 27,
        title: "Cheese",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/104615_9-amul-processed-cheese-cubes.jpg",
        price: 150,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: false
    },
    {
        id: 28,
        title: "Cream",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/40005030_2-amul-fresh-cream-25-milk-fat-low-fat.jpg",
        price: 250,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: true
    },
    {
        id: 29,
        title: "Tofu",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/40018937_8-briyas-tofu-soya-paneer.jpg",
        price: 70,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: false
    },
    {
        id: 30,
        title: "Yogurt",
        description: "Dairy",
        image: "https://www.bigbasket.com/media/uploads/p/s/40123244_5-milky-mist-fruit-yoghurt-strawberry.jpg",
        price: 60,
        discount: 5,
        quantity: 1,
        category: "Dairy",
        featured: false
    },
    {
        id: 31,
        title: "Coke",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/1223991_1-coca-cola-diet-coke-soft-drink.jpg",
        price: 80,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: true
    },
    {
        id: 32,
        title: "Soda",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/265680_11-kinley-sparkling-water-club-soda.jpg",
        price: 20,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: false
    },
    {
        id: 33,
        title: "Sprite",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/265702_11-sprite-soft-drink-lime-flavoured.jpg",
        price: 80,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: true
    },
    {
        id: 34,
        title: "ThumbsUp",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/251014_12-thums-up-soft-drink.jpg",
        price: 40,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: true
    },
    {
        id: 35,
        title: "Pepsi",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/40094179_8-pepsi-soft-drink.jpg",
        price: 40,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: false
    },
    {
        id: 36,
        title: "Schweppes",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/1224384_1-schweppes-indian-tonic-water-contains-quinine-soda-water-with-refreshing-taste.jpg",
        price: 280,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: false
    },
    {
        id: 37,
        title: "RedBull",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/40205654_3-red-bull-energy-drink-sugar-free.jpg",
        price: 100,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: true
    },
    {
        id: 38,
        title: "Mirinda",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/40094180_11-mirinda-soft-drink.jpg",
        price: 100,
        discount: 0,
        quantity: 1,
        category: "Beverages",
        featured: true
    },
    {
        id: 39,
        title: "Bisleri",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/40240300_1-bisleri-limonata-limey-minty-cooler-with-lime-juice-refreshing-ready-to-serve-fruit-based-beverage.jpg",
        price: 20,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: false
    },
    {
        id: 40,
        title: "Gatorade",
        description: "Beverages",
        image: "https://www.bigbasket.com/media/uploads/p/s/265745_10-gatorade-sports-drink-blue-bolt-flavour.jpg",
        price: 60,
        discount: 5,
        quantity: 1,
        category: "Beverages",
        featured: false
    }
]

export default items